source ~/.vim/.vimrc_bundles
source ~/.vim/.vimrc_gui
source ~/.vim/.vimrc_keybindings
source ~/.vim/.vimrc_misc
source ~/.vim/.vimrc_autogroups
source ~/.vim/.vimrc_gui
source ~/.vim/.vimrc_keybindings
source ~/.vim/.vimrc_misc
source ~/.vim/.vimrc_autogroups
